---
application:
  name: "schwi-bot"
  project: "Schwi discord bot"
  organization: "QoveryCommunity"
  cpu: 1
  ram: 700MB
  storage:
  - name: "DISK"
    size: "10"
    type: "ssd"
    mount_point: "/mnt/DISK"
routers:
- name: "main-schwi-bot"
  routes:
  - application_name: "schwi-bot"
    paths:
    - "/*"
