---
application:
  name: "schwi-bot"
  project: "test"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "MyData"
  version: "8.0"
routers:
- name: "main-schwi-bot"
  routes:
  - application_name: "schwi-bot"
    paths:
    - "/*"
