CREATE TABLE SERVER_TRACK
  (IP VARCHAR(255),
   PLATFORM VARCHAR (255),
   CONSTRAINT A_ST_PK PRIMARY KEY(IP));

CREATE TABLE CHANNEL_REPORTS
  (ID NUMERIC,
   SERV_IP VARCHAR(255),
   CONSTRAINT A_CHR_PK PRIMARY KEY(ID));
   
CREATE TABLE PLAYER_TRACK
  (NAME VARCHAR(255),
   SERV_IP VARCHAR(255),
   CHANNEL NUMERIC,
   CONSTRAINT A_PT_PK PRIMARY KEY(NAME));
   
CREATE TABLE TestTable
	(INFO1 VARCHAR(255),
	 INFO2 NUMERIC,
	 CONSTRAINT A_TT_PK PRIMARY KEY(INFO1))